version: "3.9"

services:
  db:
    image: postgres:15
    container_name: app-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  estoque:
    build:
      context: project-root/backend/estoque
      dockerfile: Dockerfile
    container_name: estoque-service
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"

  faturamento:
    build:
      context: project-root/backend/faturamento
      dockerfile: Dockerfile
    container_name: faturamento-service
    restart: unless-stopped
    depends_on:
      - db
      - estoque
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"

  angular:
    image: node:20
    container_name: angular-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm start"
    depends_on:
      - estoque
      - faturamento

volumes:
  db_data:


